### ISSUE TITLE
Do you have a fully working example?

### ISSUE THREAD

**Issue by juliomontanab** [Adnanakhter321/uhf-reader-react-native#1]
Hello! i'm trying to run the example provided in the readme.md but i think there's a problem with the latest react-native version.

Do you have any fully working example/implementation of the project in react-native JS?
I hope you do, i was looking for this solution for so much time!

Thank you!
Greetings,
Julio Montana.

**Comment by Adnanakhter321** [comment]
The latest sdk of the version is tested with 75.3 react native project, whats your version of react native project

**Comment by juliomontanab** [comment]
react-native@0.75.3 here too, but i cannot make it run with the App.tsx native implementation

**Comment by Adnanakhter321** [comment]
Email me full issue with images, you are facing on the below mentioned email : adnan.akhter321@gmail.com

@juliomontanab
